name: Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install mtools xorriso qemu qemu-system ovmf
      - name: make setup
        run: make setup
      - name: make
        run: make Inferno image iso
